<html>
<head>
<title>UNAMA - TECNOLOGIAS PARA INTERNET</title>
     <link rel="shortcut icon" href="../aula/images/GetAttachment.jpg" >
     <link rel="icon" type="image/gif" href="../aula/images/GetAttachment.jpg" >

</head>
<frameset rows=13%,5%,* cols="100%" frameborder="no">
<frame src="topo.htm" name="topo" scrolling="no" noresize="noresize" target="textos">
<frame src="menu2.htm" name="menu" scrolling="no" noresize="noresize" target="textos">
<frame src="INICIO.PHP" name="textos" target="_self" >
</frameset>
<noframes>
<P> Seu browser não suporta frames.</p>
<P> Seu browser não suporta frames.</p>
</noframes>
</frameset>
<frameset>
</frameset>
</html>