<html>
<head>
<title>Principal</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<style type="text/css">
<!--
body,td,th {
	font-family: Verdana, Arial, sans-serif;
	font-size: 12px;
	color: #306;
	font-weight: bold;
}
a:link {
	color: #306;
	text-decoration: none;
}
a:visited {
	text-decoration: none;
	color: #306;
}
a:hover {
	text-decoration: none;
	color: #0F0;
}
a:active {
	text-decoration: none;
}
-->
</style></head>

<body background="../aula/images/fundo.png" text="#306" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0">
<div align="center"> 
  <table width="70%" border="0" cellpadding="0" cellspacing="0">
    <!--DWLayoutTable-->
    <tr align="center" valign="middle"> 
      <td width="776" height="328" colspan="2"><FONT 
            face="Verdana, Arial, Helvetica, sans-serif" size=2><FONT 
            color=#330066><B>Seja bem vindo a p&aacute;gina da disciplina de TECNOLOGIAS PARA INTERNET do curso de Tecnologia da Informa&ccedil;&atilde;o da UNAMA.<br>
        </B></FONT></FONT>
        <h3>&nbsp;</h3>
      <p>P&aacute;gina desenvolvida durante as aulas da disciplina..</p>
      <p>&nbsp;</p>
      <p>Atenciosamente.</p>
      <p>&nbsp;</p>
      <p>Prof&ordm; Augusto Ba&iacute;a</p></td>
    </tr>
  </table>
</div>
</body>
</html>
